/*
 * ADC_Cfg.h
 *
 * Created: 7/11/2020 12:33:41 PM
 *  Author: nashwa.hamed
 */ 


#ifndef ADC_CFG_H_
#define ADC_CFG_H_

#define ADC_VOLTAGE_REFERENCE ADC_VREF_AVCC
#define ADC_ADJUSCENT			ADC_RIGHT_ADJUST
#define ADC_CONVERSION  ADC_AUTO_TRIGGER
#define ADC_PRESCALER  ADC_PRESC_128
#define ADC_INTERRUPT_STATUS ADC_INTERRUPT_DISABLE
#define ADC_CHANNEL		ADC_CHANNEL_1



#endif /* ADC_CFG_H_ */