/*
 * Segment.c
 *
 *  Created on: Jul 10, 2020
 *      Author: nashwa.hamed
 */
#include "Segment.h"

void Segment_Init(void){
#if SEGMANT_DEVICE==2 && SEGMANT_MODE==4
	DIO_SetPinDir(SEGMANT_ENABLE_PORT,SEGMANT_EN1,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_ENABLE_PORT,SEGMANT_EN2,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_ENABLE_PORT,SEGMANT_DIP,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN0,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN1,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN2,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN3,DIO_PIN_OUTPUT);

	//DIO_WritePin(SEGMANT_ENABLE_PORT,SEGMANT_EN1,DIO_PIN_HIGH);
	DIO_WritePin(SEGMANT_ENABLE_PORT,SEGMANT_EN2,DIO_PIN_HIGH);

#elif SEGMANT_DEVICE==1 && SEGMANT_MODE==4

	DIO_SetPinDir(SEGMANT_ENABLE_PORT,SEGMANT_EN1,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_ENABLE_PORT,SEGMANT_DIP,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN0,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN1,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN2,DIO_PIN_OUTPUT);
	DIO_SetPinDir(SEGMANT_DATA_PORT,SEGMANT_PIN3,DIO_PIN_OUTPUT);

	DIO_WritePin(SEGMANT_ENABLE_PORT,SEGMANT_EN1,DIO_PIN_HIGH);

#endif
}
void Segment_Display(uint8 val){

	//DIO_PORTA = DIO_PORTA | (val <<4);
	DIO_WritePort(DIO_PORTA, (DIO_PORTA | (val <<4)));
}
